### PR TITLE
Debroglie YD 315, a 15 key and 3 endcoder macropad

### PR DESCRIPTION
**Pull request by elffyb**
## Content
*Required:*
- Keyboard name: YD315
- Vid: 0xF1F1
- Pid: 0x0315

*Additonal info:*
- [ ] I have also submitted this keyboard to the official VIA repository (or not)
- [ ] My keyboard has an unofficial port of QMK (is not part of the main repository) (leave unchecked if official)

## Checks
- [x] At the moment of submission, the vidpid combination is unique
- [x] I understand how ViaMia works (that for others to use your submitted keyboard they have to patch their VIA install too)

### CODE REVIEW

**Comment by tkon99** [comment]
Hi there, I've removed the keyboard because it's been added to the Via database, can you confirm that this is the case? (and not just a vidpid collision)

**Comment by elffyb** [comment]
It got added on Monday yeah.
Those boys aren't sleeping on that rep anymore.  I uploaded that thinking it would sit around for months again like others, but I got a response almost immediately.  I was a little shocked.
Sorry for the double work :(
Thanks,Brett
    On Monday, August 8, 2022 at 01:44:19 PM CDT, Thomas Konings ***@***.***> wrote:  
 
 


Hi there, I've removed the keyboard because it's been added to the Via database, can you confirm that this is the case? (and not just a vidpid collision)

**Comment by tkon99** [comment]
No worries, the idea behind ViaMia is to incentivize the Via team to be more responsive so that seems to be working.

**Comment by elffyb** [comment]
Job well done.

    On Wednesday, August 10, 2022 at 03:00:45 AM CDT, Thomas Konings ***@***.***> wrote:  
 
 


No worries, the idea behind ViaMia is to incentivize the Via team to be more responsive so that seems to be working.

**Pull request merged**
