### PR TITLE
Add TKC keyboards to ViaMia

### PR DESCRIPTION
**Pull request by TerryMathews**
## Content
*Required:*
- Keyboard name: Multiple
- Vid: 0x544B
- Pid: 0x0001-0x0012

*Additonal info:*
- [X] I have also submitted this keyboard to the official VIA repository (or not)
- [ ] My keyboard has an unofficial port of QMK (is not part of the main repository) (leave unchecked if official)

## Checks
- [X] At the moment of submission, the vidpid combination is unique
- [X] I understand how ViaMia works (that for others to use your submitted keyboard they have to patch their VIA install too)

### CODE REVIEW

**Comment by tkon99** [comment]
@TerryMathews thanks for the PR. I have spotted some issues with the CI/CD pipeline and duplicate vidpids. I will resolve these and get back to you.

**Comment by TerryMathews** [comment]
@tkon99 Sounds good, happy to assist if needed. There shouldn't be any conflicts in our VID and PIDs, aside from the one that I fixed prior to merge - having it be so long since we've had a board successfully merged with The-VIA, I had reused a PID unintentionally.

**Comment by tkon99** [comment]
@TerryMathews Thanks. I have updated the build to run more verbose checks on VID and PIDs. Could you reopen a PR? I see some keyboards have already been merged in the official VIA database. Since this is used as a base by ViaMia there is no need to add these (see report below).

image

**Comment by TerryMathews** [comment]
OK, sorry I didn't realize we only needed to submit definition files that were currently missing from the main VIA repository. I'll get a new PR right over.

**Comment by tkon99** [comment]
Ah okay. Can you tell me how you expected it to work? Did you expect it to override VIA official ones or were you not aware that VIA official ones were included by default? Then I can make the documentation better.

**Comment by TerryMathews** [comment]
I had assumed this repo was independent of The-VIA's. With the discussion of the uncertainty of the licensing of these files in your docs, I guess I had assumed you were going to want the files resubmitted to clarify the licensing.

**Pull request merged**
